1-EdithWartonagino.input
2-J.F.Jameson,Ed.nwnth.input
3-J.T.Headleygrtrt.input
4-MichaelStrogoffnwyrk.input
5-OHenry4mill.input
6-StephenCranemgots.input
H.G.Wells.7mimk.input
H.G.Wells.flrgm.input
H.G.Wells.spoth.input
H.G.Wells.tditw.input
H.G.Wells.twsfr.input
H.G.Wells.wrair.input
H.G.Wells12sad.input
H.G.Wellsdmoro.input
H.G.Wellsfmitm.input
H.G.Wellsltwrs.input
H.G.Wellsnvsbl.input
H.G.Wellsrschm.input
H.G.Wellswarw1.input
H.G.Wellswchnc.input
H.G.Wellswtslw.input
JulesVerne5wiab.input
JulesVerne7robc.input
JulesVerne800lg.input
JulesVerne80day.input
JulesVerne8jrny.input
JulesVernecomet.input
JulesVernecstwy.input
JulesVernemoon.input
JulesVernestrgf.input
JulesVernethmst.input
JulesVernetsotc.input
JulesVerneucity.input
MarkTwain1prja.input
MarkTwain2prja.input
MarkTwainbeqst.input
MarkTwaincptsf.input
MarkTwainfeqtr.input
MarkTwainhdlyb.input
MarkTwainhfinn.input
MarkTwainhrstl.input
MarkTwainlmiss.input
MarkTwainlying.input
MarkTwainmtacl.input
MarkTwainmtbbg.input
MarkTwainmtccc.input
MarkTwainmtclt.input
MarkTwainmtcrg.input
MarkTwainmtcsc.input
MarkTwainmtdbd.input
MarkTwainmtdhs.input
MarkTwainmtdtl.input
MarkTwainmtext.input
MarkTwainmtfco.input
MarkTwainmtgfa.input
MarkTwainmtgld.input
MarkTwainmthdb.input
MarkTwainmthts.input
MarkTwainmtinn.input
MarkTwainmtlaf.input
MarkTwainmtmst.input
MarkTwainmtmts.input
MarkTwainmtpbg.input
MarkTwainmtrid.input
MarkTwainmtrit.input
MarkTwainmtsno.input
MarkTwainmtswe.input
MarkTwainpuddn.input
MarkTwainsawy2.input
MarkTwainsawy3.input
MarkTwainsawyr.input
MarkTwainshkdd.input
MarkTwaintramp.input
MarkTwainwman1.input
MarkTwainxadam.input
ls
